const photos = {
    defaultImage: require('../../assets/photos/defaultImage.jpg'),
    gear: require('../../assets/photos/gear.jpg'),
    gmail: require('../../assets/photos/gmail.png'),
    phone: require('../../assets/photos/phone.png'),
    linkedIn: require('../../assets/photos/linkedIn.png'),
    github: require('../../assets/photos/github.png'),
    leetcode: require('../../assets/photos/leetcode.png'),
    pdf: require('../../assets/photos/pdf.png'),
    me1: require('../../assets/photos/me1.png'),
    me2: require('../../assets/photos/me2.png'),
    view1: require('../../assets/photos/view1.jpg'),
    view2: require('../../assets/photos/view2.jpg'),
    initials: require('../../assets/photos/initials.png'),
    initialsTransparent: require('../../assets/photos/initialsTransparent.png'),
    skydive: require('../../assets/photos/skydive.jpg'),
    dance: require('../../assets/photos/dance.jpg'),
    businessCard: require('../../assets/photos/businessCard.png'),
    headshot: require('../../assets/photos/headshot.jpg'),
    generic1: require('../../assets/photos/generic1.jpg'),
    generic2: require('../../assets/photos/generic2.jpg'),
    generic3: require('../../assets/photos/generic3.jpg'),
    generic4: require('../../assets/photos/generic4.jpg'),
    generic5: require('../../assets/photos/generic5.jpg'),
    generic6: require('../../assets/photos/generic6.jpg'),
    generic7: require('../../assets/photos/generic7.jpg'),
    generic8: require('../../assets/photos/generic8.jpg'),
    generic9: require('../../assets/photos/generic9.jpg'),
    generic10: require('../../assets/photos/generic10.jpg'),
    generic11: require('../../assets/photos/generic11.jpg'),
    generic12: require('../../assets/photos/generic12.jpg'),
    generic13: require('../../assets/photos/generic13.jpg'),
    generic14: require('../../assets/photos/generic14.jpg'),
    generic15: require('../../assets/photos/generic15.jpg'),
    generic16: require('../../assets/photos/generic16.jpg'),
    generic17: require('../../assets/photos/generic17.jpg'),
    generic18: require('../../assets/photos/generic18.jpg'),
    generic19: require('../../assets/photos/generic19.jpg'),
    generic20: require('../../assets/photos/generic20.jpg'),
    generic21: require('../../assets/photos/generic21.jpg'),
    generic22: require('../../assets/photos/generic22.jpg'),
    generic23: require('../../assets/photos/generic23.jpg'),
    generic24: require('../../assets/photos/generic24.jpg'),
    generic25: require('../../assets/photos/generic25.jpg'),
    generic26: require('../../assets/photos/generic26.jpg'),
    generic27: require('../../assets/photos/generic27.jpg'),
    generic28: require('../../assets/photos/generic28.jpg'),
    generic29: require('../../assets/photos/generic29.jpg'),
    generic30: require('../../assets/photos/generic30.jpg'),
    generic31: require('../../assets/photos/generic31.jpg'),
    generic32: require('../../assets/photos/generic32.jpg'),
    generic33: require('../../assets/photos/generic33.jpg'),
    generic34: require('../../assets/photos/generic34.jpg'),
    generic35: require('../../assets/photos/generic35.jpg'),
    generic36: require('../../assets/photos/generic36.jpg'),
    generic37: require('../../assets/photos/generic37.jpg'),
    generic38: require('../../assets/photos/generic38.jpg'),
    generic39: require('../../assets/photos/generic39.jpg'),
    generic40: require('../../assets/photos/generic40.jpg'),
    generic41: require('../../assets/photos/generic41.jpg'),
    generic42: require('../../assets/photos/generic42.jpg'),
    generic43: require('../../assets/photos/generic43.jpg'),
    generic44: require('../../assets/photos/generic44.jpg'),
    generic45: require('../../assets/photos/generic45.jpg'),
    generic46: require('../../assets/photos/generic46.jpg'),
    generic47: require('../../assets/photos/generic47.jpg'),
    generic48: require('../../assets/photos/generic48.jpg'),
    generic49: require('../../assets/photos/generic49.jpg'),
    generic50: require('../../assets/photos/generic50.jpg'),
    generic51: require('../../assets/photos/generic51.jpg'),
    generic52: require('../../assets/photos/generic52.jpg'),
    generic53: require('../../assets/photos/generic53.jpg'),
    generic54: require('../../assets/photos/generic54.jpg'),
    generic55: require('../../assets/photos/generic55.jpg'),
    generic56: require('../../assets/photos/generic56.jpg'),
    generic57: require('../../assets/photos/generic57.jpg'),
    generic58: require('../../assets/photos/generic58.jpg'),
    generic59: require('../../assets/photos/generic59.jpg'),
    generic60: require('../../assets/photos/generic60.jpg'),
    generic61: require('../../assets/photos/generic61.jpg'),
    generic62: require('../../assets/photos/generic62.jpg'),
    generic63: require('../../assets/photos/generic63.jpg'),
    generic64: require('../../assets/photos/generic64.jpg'),
    generic65: require('../../assets/photos/generic65.jpg'),
    generic66: require('../../assets/photos/generic66.jpg'),
    generic67: require('../../assets/photos/generic67.jpg'),
    generic68: require('../../assets/photos/generic68.jpg'),
    generic69: require('../../assets/photos/generic69.jpg'),
    generic70: require('../../assets/photos/generic70.jpg'),
    generic71: require('../../assets/photos/generic71.jpg'),
}


export interface Photos {
    defaultImage: string;
    gear: string;
    gmail: string;
    phone: string;
    linkedIn: string;
    github: string;
    leetcode: string;
    pdf: string;
    me1: string;
    me2: string;
    view1: string;
    view2: string;
    initials: string;
    initialsTransparent: string;
    skydive: string;
    dance: string;
    businessCard: string;
    headshot: string;
    generic1: string;
    generic2: string;
    generic3: string;
    generic4: string;
    generic5: string;
    generic6: string;
    generic7: string;
    generic8: string;
    generic9: string;
    generic10: string;
    generic11: string;
    generic12: string;
    generic13: string;
    generic14: string;
    generic15: string;
    generic16: string;
    generic17: string;
    generic18: string;
    generic19: string;
    generic20: string;
    generic21: string;
    generic22: string;
    generic23: string;
    generic24: string;
    generic25: string;
    generic26: string;
    generic27: string;
    generic28: string;
    generic29: string;
    generic30: string;
    generic31: string;
    generic32: string;
    generic33: string;
    generic34: string;
    generic35: string;
    generic36: string;
    generic37: string;
    generic38: string;
    generic39: string;
    generic40: string;
    generic41: string;
    generic42: string;
    generic43: string;
    generic44: string;
    generic45: string;
    generic46: string;
    generic47: string;
    generic48: string;
    generic49: string;
    generic50: string;
    generic51: string;
    generic52: string;
    generic53: string;
    generic54: string;
    generic55: string;
    generic56: string;
    generic57: string;
    generic58: string;
    generic59: string;
    generic60: string;
    generic61: string;
    generic62: string;
    generic63: string;
    generic64: string;
    generic65: string;
    generic66: string;
    generic67: string;
    generic68: string;
    generic69: string;
    generic70: string;
    generic71: string;
}

export default photos;
